export type FileOp =
  | { kind: 'write'; path: string; content: Uint8Array }
  | { kind: 'remove'; path: string };

export interface GenerateInput {
  ops: FileOp[];
  targetSha: string;
}

export interface GeneratedScripts {
  bash: string;
  powershell: string;
  targetSha: string;
}

const BYTES_PER_LINE = 76;

function bashSingleQuote(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

function pwshSingleQuote(s: string): string {
  return `'${s.replace(/'/g, `''`)}'`;
}

function toBase64(bytes: Uint8Array): string {
  let binary = '';
  for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]!);
  if (typeof btoa === 'function') return btoa(binary);
  return Buffer.from(bytes).toString('base64');
}

function chunked(b64: string): string[] {
  const lines: string[] = [];
  for (let i = 0; i < b64.length; i += BYTES_PER_LINE) {
    lines.push(b64.slice(i, i + BYTES_PER_LINE));
  }
  return lines;
}

function validateOps(ops: FileOp[]): void {
  for (const op of ops) {
    if (!op.path) throw new Error('FileOp path must be non-empty');
    if (op.path.includes('\0')) throw new Error(`FileOp path contains NUL: ${op.path}`);
    if (op.path.startsWith('/') || op.path.includes('..'))
      throw new Error(`FileOp path must be relative inside the repo: ${op.path}`);
  }
}

function emitBash(ops: FileOp[], targetSha: string): string {
  const out: string[] = [];
  out.push('#!/usr/bin/env bash');
  out.push('# Generated by GitClip — applies a commit by writing files in place.');
  out.push(`# Target commit: ${targetSha}`);
  out.push('set -euo pipefail');
  out.push('');
  out.push('_gc_root=$PWD');
  out.push('_gc_dir=$PWD');
  out.push('while [ "$_gc_dir" != "/" ] && [ -n "$_gc_dir" ]; do');
  out.push('  if [ -f "$_gc_dir/.gitclip-head" ]; then _gc_root=$_gc_dir; break; fi');
  out.push('  _gc_dir=$(dirname "$_gc_dir")');
  out.push('done');
  out.push('cd "$_gc_root"');
  out.push('echo "GitClip: applying in $_gc_root"');
  out.push('');
  out.push('_gc_write() {');
  out.push('  local path=$1');
  out.push('  local dir');
  out.push('  dir=$(dirname "$path")');
  out.push('  [ "$dir" = "." ] || mkdir -p "$dir"');
  out.push('  base64 -d > "$path"');
  out.push('}');
  out.push('');

  for (const op of ops) {
    if (op.kind === 'remove') {
      out.push(`rm -f -- ${bashSingleQuote(op.path)}`);
    } else {
      const lines = chunked(toBase64(op.content));
      out.push(`_gc_write ${bashSingleQuote(op.path)} <<'GITCLIP_B64'`);
      for (const line of lines) out.push(line);
      out.push('GITCLIP_B64');
    }
  }

  out.push('');
  out.push(`printf '%s\\n' ${bashSingleQuote(targetSha)} > .gitclip-head`);
  out.push(`echo "GitClip: now at ${targetSha}"`);
  return out.join('\n') + '\n';
}

function emitPowerShell(ops: FileOp[], targetSha: string): string {
  const out: string[] = [];
  out.push('# Generated by GitClip — applies a commit by writing files in place.');
  out.push(`# Target commit: ${targetSha}`);
  out.push("$ErrorActionPreference = 'Stop'");
  out.push('');
  out.push('$_gcRoot = (Get-Location).Path');
  out.push('$_gcDir = $_gcRoot');
  out.push('while ($_gcDir) {');
  out.push("  if (Test-Path -LiteralPath (Join-Path $_gcDir '.gitclip-head')) { $_gcRoot = $_gcDir; break }");
  out.push('  $_gcParent = Split-Path -Parent $_gcDir');
  out.push('  if (-not $_gcParent -or $_gcParent -eq $_gcDir) { break }');
  out.push('  $_gcDir = $_gcParent');
  out.push('}');
  out.push('Set-Location -LiteralPath $_gcRoot');
  out.push('Write-Host "GitClip: applying in $_gcRoot"');
  out.push('');
  out.push('function _Gc-Write {');
  out.push('  param([string]$Path, [string]$B64)');
  out.push('  $dir = Split-Path -Parent $Path');
  out.push('  if ($dir -and -not (Test-Path -LiteralPath $dir)) {');
  out.push('    New-Item -ItemType Directory -Force -Path $dir | Out-Null');
  out.push('  }');
  out.push('  [IO.File]::WriteAllBytes((Resolve-Path -LiteralPath . | Join-Path -ChildPath $Path), [Convert]::FromBase64String($B64))');
  out.push('}');
  out.push('');

  for (const op of ops) {
    if (op.kind === 'remove') {
      out.push(
        `Remove-Item -LiteralPath ${pwshSingleQuote(op.path)} -Force -ErrorAction SilentlyContinue`,
      );
    } else {
      const b64 = toBase64(op.content);
      out.push(`_Gc-Write -Path ${pwshSingleQuote(op.path)} -B64 ${pwshSingleQuote(b64)}`);
    }
  }

  out.push('');
  out.push(
    `Set-Content -LiteralPath .gitclip-head -Value ${pwshSingleQuote(targetSha)} -NoNewline -Encoding utf8`,
  );
  out.push(`Write-Host "GitClip: now at ${targetSha}"`);
  return out.join('\r\n') + '\r\n';
}

export function generateScripts(input: GenerateInput): GeneratedScripts {
  validateOps(input.ops);
  return {
    bash: emitBash(input.ops, input.targetSha),
    powershell: emitPowerShell(input.ops, input.targetSha),
    targetSha: input.targetSha,
  };
}

export function estimatedSize(scripts: GeneratedScripts): number {
  return scripts.bash.length + scripts.powershell.length;
}
