export type FileOp =
  | { kind: 'write'; path: string; content: Uint8Array }
  | { kind: 'remove'; path: string };

export interface GenerateInput {
  ops: FileOp[];
  targetSha: string;
  fromSha: string;
}

export interface GeneratedScripts {
  bash: string;
  powershell: string;
  targetSha: string;
}

const BYTES_PER_LINE = 76;

function bashSingleQuote(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

function pwshSingleQuote(s: string): string {
  return `'${s.replace(/'/g, `''`)}'`;
}

function toBase64(bytes: Uint8Array): string {
  let binary = '';
  for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]!);
  if (typeof btoa === 'function') return btoa(binary);
  return Buffer.from(bytes).toString('base64');
}

function chunked(b64: string): string[] {
  const lines: string[] = [];
  for (let i = 0; i < b64.length; i += BYTES_PER_LINE) {
    lines.push(b64.slice(i, i + BYTES_PER_LINE));
  }
  return lines;
}

function validateOps(ops: FileOp[]): void {
  for (const op of ops) {
    if (!op.path) throw new Error('FileOp path must be non-empty');
    if (op.path.includes('\0')) throw new Error(`FileOp path contains NUL: ${op.path}`);
    if (op.path.startsWith('/') || op.path.includes('..'))
      throw new Error(`FileOp path must be relative inside the repo: ${op.path}`);
  }
}

function validateSha(sha: string, label: string): void {
  if (!/^[0-9a-fA-F]{7,40}$/.test(sha)) {
    throw new Error(`${label} must be 7-40 hex chars: ${sha}`);
  }
}

function emitBash(ops: FileOp[], targetSha: string, fromSha: string): string {
  const out: string[] = [];
  out.push('#!/usr/bin/env bash');
  out.push('# GITCLIP/1');
  out.push('# Generated by GitClip — applies a commit by writing files in place.');
  out.push(`# Target commit: ${targetSha}`);
  out.push(`# Expected anchor (.gitclip-head): ${fromSha}`);
  out.push('(');
  out.push('set -euo pipefail');
  out.push(`_gc_expect=${bashSingleQuote(fromSha.toLowerCase())}`);
  out.push('_gc_force=${GITCLIP_FORCE:-0}');
  out.push('_gc_root=$PWD');
  out.push('_gc_dir=$PWD');
  out.push('_gc_anchor=');
  out.push('while [ "$_gc_dir" != "/" ] && [ -n "$_gc_dir" ]; do');
  out.push('  if [ -f "$_gc_dir/.gitclip-head" ]; then');
  out.push('    _gc_root=$_gc_dir');
  out.push('    _gc_anchor=$_gc_dir/.gitclip-head');
  out.push('    break');
  out.push('  fi');
  out.push('  _gc_dir=$(dirname "$_gc_dir")');
  out.push('done');
  out.push('');
  out.push('if [ -n "$_gc_anchor" ]; then');
  out.push('  _gc_found=$(tr -d "[:space:]" < "$_gc_anchor" | tr "[:upper:]" "[:lower:]")');
  out.push('  _gc_match=0');
  out.push('  case "$_gc_found" in "$_gc_expect"*) _gc_match=1 ;; esac');
  out.push('  case "$_gc_expect" in "$_gc_found"*) _gc_match=1 ;; esac');
  out.push('  if [ "$_gc_match" -ne 1 ]; then');
  out.push('    if [ "$_gc_force" = "1" ]; then');
  out.push('      echo "GitClip: anchor mismatch (have $_gc_found, paste expects $_gc_expect) — GITCLIP_FORCE=1, proceeding" >&2');
  out.push('    else');
  out.push('      echo "GitClip error: .gitclip-head at $_gc_anchor is $_gc_found, paste expects $_gc_expect." >&2');
  out.push('      echo "Regenerate paste from $_gc_found, or set GITCLIP_FORCE=1 to override." >&2');
  out.push('      exit 1');
  out.push('    fi');
  out.push('  fi');
  out.push('else');
  out.push('  if [ "$_gc_force" = "1" ]; then');
  out.push('    echo "GitClip: no .gitclip-head found — GITCLIP_FORCE=1, applying in $_gc_root" >&2');
  out.push('  elif { exec 9<>/dev/tty; } 2>/dev/null; then');
  out.push('    printf "No .gitclip-head found. Apply in %s anyway? [y/N]: " "$_gc_root" >&9');
  out.push('    IFS= read -r _gc_reply <&9 || _gc_reply=');
  out.push('    exec 9<&-');
  out.push('    case "$_gc_reply" in');
  out.push('      y|Y|yes|YES|Yes) ;;');
  out.push('      *) echo "GitClip: aborted." >&2; exit 1 ;;');
  out.push('    esac');
  out.push('  else');
  out.push('    echo "GitClip error: no .gitclip-head found and no TTY for confirmation." >&2');
  out.push('    echo "Set GITCLIP_FORCE=1 to apply in $_gc_root anyway." >&2');
  out.push('    exit 1');
  out.push('  fi');
  out.push('fi');
  out.push('');
  out.push('cd "$_gc_root"');
  out.push('echo "GitClip: applying in $_gc_root"');
  out.push('');
  out.push('_gc_write() {');
  out.push('  local path=$1');
  out.push('  local dir');
  out.push('  dir=$(dirname "$path")');
  out.push('  [ "$dir" = "." ] || mkdir -p "$dir"');
  out.push('  base64 -d > "$path"');
  out.push('}');
  out.push('');

  for (const op of ops) {
    if (op.kind === 'remove') {
      out.push(`rm -f -- ${bashSingleQuote(op.path)}`);
    } else {
      const lines = chunked(toBase64(op.content));
      out.push(`_gc_write ${bashSingleQuote(op.path)} <<'GITCLIP_B64'`);
      for (const line of lines) out.push(line);
      out.push('GITCLIP_B64');
    }
  }

  out.push('');
  out.push(`printf '%s\\n' ${bashSingleQuote(targetSha)} > .gitclip-head`);
  out.push(`echo "GitClip: now at ${targetSha}"`);
  out.push(')');
  return out.join('\n') + '\n';
}

function emitPowerShell(ops: FileOp[], targetSha: string, fromSha: string): string {
  const out: string[] = [];
  out.push('#!GITCLIP/1');
  out.push('# Generated by GitClip — applies a commit by writing files in place.');
  out.push(`# Target commit: ${targetSha}`);
  out.push(`# Expected anchor (.gitclip-head): ${fromSha}`);
  out.push("$ErrorActionPreference = 'Stop'");
  out.push(`$_gcExpect = ${pwshSingleQuote(fromSha.toLowerCase())}`);
  out.push("$_gcForce = ($env:GITCLIP_FORCE -eq '1')");
  out.push('$_gcRoot = (Get-Location).Path');
  out.push('$_gcDir = $_gcRoot');
  out.push('$_gcAnchor = $null');
  out.push('while ($_gcDir) {');
  out.push("  $_gcCandidate = Join-Path $_gcDir '.gitclip-head'");
  out.push('  if (Test-Path -LiteralPath $_gcCandidate) {');
  out.push('    $_gcRoot = $_gcDir');
  out.push('    $_gcAnchor = $_gcCandidate');
  out.push('    break');
  out.push('  }');
  out.push('  $_gcParent = Split-Path -Parent $_gcDir');
  out.push('  if (-not $_gcParent -or $_gcParent -eq $_gcDir) { break }');
  out.push('  $_gcDir = $_gcParent');
  out.push('}');
  out.push('');
  out.push('if ($_gcAnchor) {');
  out.push('  $_gcFound = ((Get-Content -LiteralPath $_gcAnchor -Raw) -replace "\\s","").ToLower()');
  out.push('  $_gcMatch = $_gcFound.StartsWith($_gcExpect) -or $_gcExpect.StartsWith($_gcFound)');
  out.push('  if (-not $_gcMatch) {');
  out.push('    if ($_gcForce) {');
  out.push('      Write-Host "GitClip: anchor mismatch (have $_gcFound, paste expects $_gcExpect) — GITCLIP_FORCE=1, proceeding"');
  out.push('    } else {');
  out.push('      [Console]::Error.WriteLine("GitClip error: .gitclip-head at $_gcAnchor is $_gcFound, paste expects $_gcExpect.")');
  out.push('      [Console]::Error.WriteLine("Regenerate paste from $_gcFound, or set GITCLIP_FORCE=1 to override.")');
  out.push('      throw "GitClip: anchor mismatch"');
  out.push('    }');
  out.push('  }');
  out.push('} else {');
  out.push('  if ($_gcForce) {');
  out.push('    Write-Host "GitClip: no .gitclip-head found — GITCLIP_FORCE=1, applying in $_gcRoot"');
  out.push('  } else {');
  out.push('    $_gcReply = $null');
  out.push('    try {');
  out.push('      [Console]::Out.Write("No .gitclip-head found. Apply in $_gcRoot anyway? [y/N]: ")');
  out.push('      $_gcReply = [Console]::In.ReadLine()');
  out.push('    } catch {');
  out.push('      [Console]::Error.WriteLine("GitClip error: no .gitclip-head found and no interactive console.")');
  out.push('      [Console]::Error.WriteLine("Set GITCLIP_FORCE=1 to apply in $_gcRoot anyway.")');
  out.push('      throw "GitClip: no anchor and no interactive console"');
  out.push('    }');
  out.push('    if ($_gcReply -notmatch "^(y|Y|yes|YES|Yes)$") {');
  out.push('      Write-Host "GitClip: aborted."');
  out.push('      throw "GitClip: aborted by user"');
  out.push('    }');
  out.push('  }');
  out.push('}');
  out.push('');
  out.push('Push-Location -LiteralPath $_gcRoot');
  out.push('try {');
  out.push('Write-Host "GitClip: applying in $_gcRoot"');
  out.push('');
  out.push('function _Gc-Write {');
  out.push('  param([string]$Path, [string]$B64)');
  out.push('  $dir = Split-Path -Parent $Path');
  out.push('  if ($dir -and -not (Test-Path -LiteralPath $dir)) {');
  out.push('    New-Item -ItemType Directory -Force -Path $dir | Out-Null');
  out.push('  }');
  out.push('  [IO.File]::WriteAllBytes((Resolve-Path -LiteralPath . | Join-Path -ChildPath $Path), [Convert]::FromBase64String($B64))');
  out.push('}');
  out.push('');

  for (const op of ops) {
    if (op.kind === 'remove') {
      out.push(
        `Remove-Item -LiteralPath ${pwshSingleQuote(op.path)} -Force -ErrorAction SilentlyContinue`,
      );
    } else {
      const b64 = toBase64(op.content);
      out.push(`_Gc-Write -Path ${pwshSingleQuote(op.path)} -B64 ${pwshSingleQuote(b64)}`);
    }
  }

  out.push('');
  out.push(
    `Set-Content -LiteralPath .gitclip-head -Value ${pwshSingleQuote(targetSha)} -NoNewline -Encoding utf8`,
  );
  out.push(`Write-Host "GitClip: now at ${targetSha}"`);
  out.push('} finally { Pop-Location }');
  return out.join('\r\n') + '\r\n';
}

export function generateScripts(input: GenerateInput): GeneratedScripts {
  validateOps(input.ops);
  validateSha(input.targetSha, 'targetSha');
  validateSha(input.fromSha, 'fromSha');
  return {
    bash: emitBash(input.ops, input.targetSha, input.fromSha),
    powershell: emitPowerShell(input.ops, input.targetSha, input.fromSha),
    targetSha: input.targetSha,
  };
}

export function estimatedSize(scripts: GeneratedScripts): number {
  return scripts.bash.length + scripts.powershell.length;
}
